directed: true
graph: {}
links:
- capacity: 3
  name: e1
  source: o
  target: a
- capacity: 3
  name: e3
  source: o
  target: b
- capacity: 2
  name: e2
  source: a
  target: d
- capacity: 2
  name: e4
  source: b
  target: d
- capacity: 3
  name: e5
  source: b
  target: c
- capacity: 1
  name: e6
  source: c
  target: d
multigraph: false
nodes:
- color: red
  id: o
  pos: !!python/tuple
  - 0
  - 0
- color: blue
  id: a
  pos: !!python/tuple
  - 0.5
  - 0.5
- color: blue
  id: b
  pos: !!python/tuple
  - 0.5
  - 0
- color: green
  id: d
  pos: !!python/tuple
  - 1
  - 0
- color: blue
  id: c
  pos: !!python/tuple
  - 0.5
  - -0.5
