edges:
- - o
  - a
  - capacity: 3
    name: e1
- - o
  - b
  - capacity: 3
    name: e3
- - a
  - d
  - capacity: 2
    name: e2
- - b
  - d
  - capacity: 2
    name: e4
- - b
  - c
  - capacity: 3
    name: e5
- - c
  - d
  - capacity: 1
    name: e6
nodes:
- - o
  - color: red
    pos:
    - 0
    - 0
- - d
  - color: green
    pos:
    - 1
    - 0
- - a
  - color: blue
    pos:
    - 0.5
    - 0.5
- - b
  - color: blue
    pos:
    - 0.5
    - 0
- - c
  - color: blue
    pos:
    - 0.5
    - -0.5
